CREATE TABLE `message_queue` (
  `message_id` char(35) COLLATE utf8_unicode_ci NOT NULL,
  `message_status` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT 'Status of the message. 0: Waiting, 1: Popped, 2: No response, 3: To delete ',
  `message_priority` smallint(5) unsigned NOT NULL DEFAULT '3' COMMENT 'Priority: 1: Very high, 2: High, 3: Medium, 4: Low, 5: Very low',
  `message_topic` varchar(100) CHARACTER SET utf8 NOT NULL COMMENT 'Topic of the message (ie: publish.content).',
  `message_content` text CHARACTER SET utf8 NOT NULL COMMENT 'Message content.',
  `message_content_type` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'text' COMMENT 'Message type.',
  `message_entity_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Entity identifier linked to the message, if exist.',
  `message_date_expiration` datetime DEFAULT NULL COMMENT 'Expiration date for the message. If null, message does not expire.',
  `message_date_availability` datetime DEFAULT NULL COMMENT 'Availability Date for the message. Before this date, message is not available',
  `message_pending_id` varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Pending id generated to avoid message to be consumed by 2 scripts in parallel',
  `message_date_create` datetime NOT NULL COMMENT 'Creation date for the message.',
  `message_date_update` datetime DEFAULT NULL COMMENT 'Update date for the message.',
  PRIMARY KEY (`message_id`),
  KEY `idx_message_priority` (`message_priority`),
  KEY `idx_message_date_availability` (`message_date_availability`),
  KEY `idx_message_date_expiration` (`message_date_expiration`),
  KEY `idx_message_topic` (`message_topic`),
  KEY `idx_message_entity` (`message_entity_id`),
  KEY `idx_message_status` (`message_status`),
  KEY `idx_message_date_create` (`message_date_create`),
  KEY `idx_message_date_update` (`message_date_update`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
